#!/bin/zsh

for dir in */; do
    if [[ $dir == "PolyModLoader/" ]]; then continue; fi
    pandoc -f markdown -t html $dir/description.md -o $dir/description.html --lua-filter pandoc-filter.lua
    tsc $dir/main.mod.ts --target ES2020 --module ES2020
done

if [[ "$1" == "host" ]]; then
    trap "trap - TERM && kill -- -$$" INT TERM EXIT
    (cd PolyModLoader; python ../httpserver.py 8000 &> /dev/null) &
    python httpserver.py 8001 &> /dev/null &
    wait
fi
